#' Custom Fill Color Scale Using China Traditional Colors
#'
#' Creates a ggplot2 fill scale using colors from `chinacolor` dataset,
#' with color selection controlled by a `color_pick` list generated by `create_color_pick()`.
#'
#' @param palette A vector of hex color codes (ignored if `color_pick` is provided).
#' @param color_pick A list generated by `create_color_pick()`, specifying:
#'   - `color_id`: Directly selected color IDs (optional).
#'   - `group_info`: List with `group` (vector of group numbers) and `subgroup` (list of subgroups per group) (optional).
#'   - `order`: Sorting rule (1: input order; 0: ascending ID; -1: descending ID).
#' @param direction 1 (default) for original color order, -1 to reverse.
#' @param ... Additional arguments passed to `ggplot2::scale_fill_manual()`.
#'
#' @return A ggplot2 fill scale object.
#'
#' @examples
#' \dontrun{
#' # Step 1: Generate color_pick using create_color_pick()
#' my_pick <- create_color_pick(
#'   groups = c(3, 5),          # Select color groups 3 and 5
#'   subgroups = list(c(1, 3), 2),  # Subgroups 1&3 for group 3; subgroup 2 for group 5
#'   order_rule = 0             # Sort by color ID ascending
#' )
#'
#' # Step 2: Use in ggplot with scale_fill_ctc_m
#' ggplot(iris, aes(Sepal.Length, Sepal.Width, fill = Species)) +
#'   geom_point(shape = 21, size = 3) +
#'   scale_fill_ctc_m(color_pick = my_pick)  # Pass the generated color_pick
#' }
#'
#' @seealso `create_color_pick()` for generating `color_pick`;
#'          `ctc_palette()` for how colors are selected from `chinacolor`.
#' @export
scale_fill_ctc_m <- function(palette = NULL,
                             color_pick = NULL,
                             direction = 1,
                             ...) {

    # Validate color_pick is generated by create_color_pick()
    if (!is.null(color_pick)) {
        if (!is.list(color_pick) || !all(c("order") %in% names(color_pick)) ||
            (is.null(color_pick$color_id) && is.null(color_pick$group_info))) {
            stop("'color_pick' must be a list generated by create_color_pick().")
        }
    }

    # Get colors from ctc_palette (using color_pick or palette)
    if (!is.null(color_pick)) {
        colors <- ctc_palette(
            type = "custom",
            color_pick = color_pick,
            direction = direction
        )
    } else {
        if (is.null(palette)) {
            stop("Provide either 'palette' (color vector) or 'color_pick' (from create_color_pick()).")
        }
        colors <- palette
    }

    scale_fill_manual(values = colors, ...)
}


#' Custom Outline Color Scale Using China Traditional Colors
#'
#' Creates a ggplot2 outline color scale using colors from `chinacolor` dataset,
#' with color selection controlled by a `color_pick` list generated by `create_color_pick()`.
#'
#' @param palette A vector of hex color codes (ignored if `color_pick` is provided).
#' @param color_pick A list generated by `create_color_pick()`, specifying:
#'   - `color_id`: Directly selected color IDs (optional).
#'   - `group_info`: List with `group` (vector of group numbers) and `subgroup` (list of subgroups per group) (optional).
#'   - `order`: Sorting rule (1: input order; 0: ascending ID; -1: descending ID).
#' @param direction 1 (default) for original color order, -1 to reverse.
#' @param ... Additional arguments passed to `ggplot2::scale_color_manual()`.
#'
#' @return A ggplot2 outline color scale object.
#'
#' @examples
#' \dontrun{
#' # Step 1: Generate color_pick with specific color IDs and sorting
#' my_pick <- create_color_pick(
#'   color_id = c(124, 324, 44),  # Directly select colors by ID
#'   order_rule = -1            # Sort by ID descending
#' )
#'
#' # Step 2: Use in ggplot with scale_colour_ctc_m
#' ggplot(mtcars, aes(mpg, wt, color = factor(cyl))) +
#'   geom_point(size = 3) +
#'   scale_colour_ctc_m(color_pick = my_pick) + # Pass the generated color_pick
#'   theme_ctc_paper()
#' }
#'
#' @seealso `create_color_pick()` for generating `color_pick`;
#'          `ctc_palette()` for how colors are selected from `chinacolor`.
#' @export
scale_colour_ctc_m <- function(palette = NULL,
                               color_pick = NULL,
                               direction = 1,
                               ...) {

    # Validate color_pick structure
    if (!is.null(color_pick)) {
        if (!is.list(color_pick) || !all(c("order") %in% names(color_pick)) ||
            (is.null(color_pick$color_id) && is.null(color_pick$group_info))) {
            stop("'color_pick' must be a list generated by create_color_pick().")
        }
    }

    # Get colors from ctc_palette
    if (!is.null(color_pick)) {
        colors <- ctc_palette(
            type = "custom",
            color_pick = color_pick,
            direction = direction
        )
    } else {
        if (is.null(palette)) {
            stop("Provide either 'palette' (color vector) or 'color_pick' (from create_color_pick()).")
        }
        colors <- palette
    }

    # Reverse order if needed
    if (direction == -1) {
        colors <- rev(colors)
    }

    scale_color_manual(values = colors, ...)
}
# Alias for scale_color_ctc_m  (American English Spelling)
#' @rdname scale_colour_ctc_m
#' @export
scale_color_ctc_m <- scale_colour_ctc_m
